// SPDX-FileCopyrightText: 2026 folknor
// SPDX-License-Identifier: AGPL-3.0-only

//! Out-of-band control plane: arm deterministic divergences for tests.
//!
//! This is the reason mogwai exists as an external process - it can emit ugly,
//! realistic event streams an in-process matching engine never would, to drive
//! a host's error-classification and brake/quarantine/restart layer.

use crate::{ClientOrderId, Decimal, Deserialize, Serialize};

/// The decimal spelling of the bound as a number. A `const fn` because that is
/// what lets the bound and the refusal texts below share one written spelling
/// instead of each carrying its own.
const fn parse_ms(text: &str) -> u64 {
    let bytes = text.as_bytes();
    let mut value = 0u64;
    let mut at = 0;
    while at < bytes.len() {
        assert!(
            bytes[at].is_ascii_digit(),
            "the bound's spelling must be decimal digits"
        );
        // `u64::from` is a trait method, so it is unavailable in a const fn.
        value = value * 10 + (bytes[at] - b'0') as u64;
        at += 1;
    }
    value
}

/// The bound and every refusal that quotes it, from one written spelling.
///
/// The validators return `&'static str` and Rust has no const formatting, so a
/// message naming the ceiling has to splice a literal in at compile time. Doing
/// that here, off the same literal the bound itself is parsed from, is what
/// keeps the hour written once: the alternative is a message that goes on
/// quoting an old ceiling after the bound moves, with nothing able to notice.
macro_rules! divergence_bound {
    ($spelled:literal) => {
        /// Upper bound on any single divergence's `ms` window, enforced by
        /// `validate_divergence`.
        ///
        /// One hour is far longer than any test blackout, data-stall, or
        /// ack-delay scenario needs, and an hour expressed in nanoseconds is
        /// well below `u64::MAX`, so validated temporal windows cannot saturate
        /// writer deadlines.
        pub const MAX_DIVERGENCE_MS: u64 = parse_ms($spelled);

        /// Refusal text for an over-range `GeneratorArm::normalize` duration.
        pub(crate) const REFUSE_GENERATOR_DURATION: &str =
            concat!("generator duration_ms must be <= ", $spelled);
        /// Refusal text shared by the three single-window divergences.
        pub(crate) const REFUSE_WINDOW_MS: &str = concat!(
            "DelayAcks/GoDark/StallData ms must be <= ",
            $spelled,
            " (one hour)"
        );
        /// Refusal text for any over-range `CommandLatency` field.
        pub(crate) const REFUSE_COMMAND_LATENCY: &str = concat!(
            "CommandLatency fields must each be <= ",
            $spelled,
            " (one hour)"
        );
        /// Refusal text for an over-range `FeeSurcharge` window.
        pub(crate) const REFUSE_FEE_WINDOW: &str =
            concat!("FeeSurcharge window_ms must be <= ", $spelled);
    };
}

divergence_bound!("3600000");

/// Fixed-point scale for a generator multiplier: parts per million.
pub const GENERATOR_MULT_SCALE: u64 = 1_000_000;

/// A generator arm in the form river identity is keyed on.
///
/// Generator havoc changes the water rather than one passenger's view of it, so
/// it is part of which river a passenger boards rather than something done to a
/// river that already exists. That is why this is a type of its own instead of
/// a `Divergence` variant: a transport arm is judged on each reader's own clock
/// and blurs what that reader receives, while this is a property of the water
/// and every reader of that water sees the same thing.
///
/// Two things make it usable as identity. The window is a coordinate on the
/// river rather than a deadline: `start_offset_ns` counts from the run origin,
/// so two passengers naming the same window get the same water whenever they
/// board, where "starting when I connect" would fork a river per boarding
/// instant and share nothing. And the multipliers are fixed point, because
/// identity is an equality question and equivalent human inputs do not produce
/// equal floats - `1.1`, `11.0 / 10.0` and a JSON-decoded decimal can differ in
/// the last bit and would each strand a river of their own against a cap that
/// never evicts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GeneratorArm {
    /// Offset from the run origin at which the window opens.
    pub start_offset_ns: u64,
    pub duration_ms: u64,
    /// Parent arrival multiplier, in units of `GENERATOR_MULT_SCALE`.
    pub rate_mult_ppm: u64,
    /// Sweep-size multiplier, in units of `GENERATOR_MULT_SCALE`.
    pub children_mult_ppm: u64,
}

impl GeneratorArm {
    /// Normalize a requested arm, or refuse it.
    ///
    /// `Ok(None)` is a legal request that changes no generated byte - a zero
    /// duration, or both multipliers at unity - and it collapses to no arm at
    /// all so that a harness spelling "no havoc" explicitly boards the same
    /// river as one that says nothing. An arm whose window has closed does not
    /// collapse: it changed the warmup, the history and the generator's
    /// path-dependent state, so the water after it differs from water that
    /// never had it, and calling those the same river would hand a passenger a
    /// realization it did not ask for.
    pub fn normalize(
        start_offset_ns: u64,
        duration_ms: u64,
        rate_mult: f64,
        children_mult: f64,
    ) -> Result<Option<Self>, &'static str> {
        if !rate_mult.is_finite() || !(1.0..=1000.0).contains(&rate_mult) {
            return Err("generator rate_mult must be in [1, 1000]");
        }
        if !children_mult.is_finite() || !(1.0..=100.0).contains(&children_mult) {
            return Err("generator children_mult must be in [1, 100]");
        }
        if duration_ms > MAX_DIVERGENCE_MS {
            return Err(REFUSE_GENERATOR_DURATION);
        }
        let scale = |value: f64| -> u64 {
            #[expect(
                clippy::cast_possible_truncation,
                clippy::cast_sign_loss,
                reason = "bounded above by 1000 and below by 1 immediately above, so the scaled value is far inside u64"
            )]
            {
                (value * GENERATOR_MULT_SCALE as f64).round() as u64
            }
        };
        let rate_mult_ppm = scale(rate_mult);
        let children_mult_ppm = scale(children_mult);
        // Decided after scaling, so a multiplier that is neutral only once
        // canonicalized collapses too, rather than keying a river that
        // generates identically to the clean one.
        if duration_ms == 0
            || (rate_mult_ppm == GENERATOR_MULT_SCALE && children_mult_ppm == GENERATOR_MULT_SCALE)
        {
            return Ok(None);
        }
        Ok(Some(Self {
            start_offset_ns,
            duration_ms,
            rate_mult_ppm,
            children_mult_ppm,
        }))
    }

    #[must_use]
    pub fn rate_mult(self) -> f64 {
        #[expect(
            clippy::cast_precision_loss,
            reason = "at most 1e9, exactly representable"
        )]
        {
            self.rate_mult_ppm as f64 / GENERATOR_MULT_SCALE as f64
        }
    }

    #[must_use]
    pub fn children_mult(self) -> f64 {
        #[expect(
            clippy::cast_precision_loss,
            reason = "at most 1e8, exactly representable"
        )]
        {
            self.children_mult_ppm as f64 / GENERATOR_MULT_SCALE as f64
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Divergence {
    /// Fill the next matching order only `fraction` of the way, leaving the rest open.
    PartialFillNext {
        client_order_id: ClientOrderId,
        fraction: Decimal,
    },
    /// Reject the next submitted order with `reason`.
    RejectNextSubmit { reason: String },
    /// Refuse the next `CancelOrder` with `reason`, leaving the order resting.
    ///
    /// The mirror of `RejectNextSubmit`, and it exists because nothing else can
    /// produce the shape: a consumer that publishes a replacement before its
    /// cancel is acknowledged, and then has the cancel refused, is left with two
    /// live orders where its script rests one. That is a real live-path defect a
    /// consumer fixed and could pin only with in-process tests, because no venue
    /// could provoke it.
    ///
    /// Distinct from the order being unknown or already terminal, which produce
    /// the same frame for real reasons. This one refuses a cancel the venue
    /// could have honoured, so the order stays exactly what it was - the point
    /// is that the book and the consumer's model disagree afterwards.
    RejectNextCancel { reason: String },
    /// Delay every outbound execution event by `ms`, bounded by
    /// `MAX_DIVERGENCE_MS`. Arm with `ms: 0` to clear: that is the only route
    /// off it, and it releases acknowledgements already queued, because the
    /// writer reads the window per event at dequeue. It does not reach an act
    /// delay already being served.
    DelayAcks { ms: u64 },
    /// Per-command venue latency: how long the venue takes to act on each order
    /// command, and how long it then takes to ack what it did.
    ///
    /// Every field is milliseconds on the sim axis, bounded by
    /// `MAX_DIVERGENCE_MS`, and adds to any armed `DelayAcks` rather than
    /// replacing it (the same composition rule `BASELINE_LATENCY` states for the
    /// adapter's inbound latency) - though that addition happens in the WS pump,
    /// which is the only place `DelayAcks` applies at all. An arm replaces all
    /// six values; an omitted field is zero. Re-arming with every field omitted
    /// is therefore the route off it, and it is the only one: an act delay the
    /// venue has already begun serving sleeps out its full window and then
    /// mutates, because a venue that has begun acting does not un-begin.
    CommandLatency {
        #[serde(default)]
        submit_act_ms: u64,
        #[serde(default)]
        modify_act_ms: u64,
        #[serde(default)]
        cancel_act_ms: u64,
        #[serde(default)]
        submit_ack_ms: u64,
        #[serde(default)]
        modify_ack_ms: u64,
        #[serde(default)]
        cancel_ack_ms: u64,
    },
    /// Emit the next fill event twice.
    DuplicateNextFill,
    /// Swallow the next account-state update that follows an order executing or
    /// leaving the book (induce account drift). A fill qualifies, and so does a
    /// cancel freeing a resting order's hold, a funds-check eviction, and a stop
    /// trigger that booked either. An order merely coming to rest does not,
    /// even though its hold moves `locked`: acceptance always precedes
    /// the fill, so an arm spent there could never reach what it was aimed at.
    DropNextAccountUpdate,
    /// Stop sending anything for `ms` (simulate a venue blackout), bounded
    /// by `MAX_DIVERGENCE_MS`. Frames produced during the window are
    /// dropped, not buffered. Re-arm with `ms: 0` to lift the window early;
    /// a re-arm replaces the window outright rather than extending it.
    GoDark { ms: u64 },
    /// Suppress only market-data frames (`Trade` / `Quote`) for `ms`,
    /// leaving every execution frame alive. Bounded by
    /// `MAX_DIVERGENCE_MS`. Frames produced during the window are dropped,
    /// not buffered. Re-arm with `ms: 0` to lift the window early.
    ///
    /// Unlike `GoDark`, this keeps the socket healthy while only channel
    /// data is withheld, especially when paired with the venue
    /// `Heartbeat`.
    StallData { ms: u64 },
    /// Temporarily multiply the configured maker/taker charge in sim time.
    FeeSurcharge { mult: Decimal, window_ms: u64 },
    /// Cancel a resting order venue-side, immediately, emitting no lifecycle
    /// event - the out-of-band cancel with a lost `OrderCanceled` that the
    /// consumer's reconciliation poll exists to catch. Unlike the armed
    /// single-shot divergences this is not queued for a trigger: it acts on
    /// the book the moment it is posted (there is no consumer action to key
    /// off), frees the order's hold, and leaves the consumer believing
    /// the order still rests until it reconciles - a `QueryOrders` reply
    /// truthfully reports the order `Canceled` from then on. Posting it for
    /// an id that is not currently resting is refused with a 4xx, so a
    /// scenario cannot silently arm a no-op.
    CancelOpenOrderSilently { client_order_id: ClientOrderId },
    /// Fault the venue's tape terminally: the run reports a source fault on
    /// `/health`, tears down, and the process exits nonzero.
    ///
    /// The venue dying is itself a divergence, and the one a consumer is least
    /// likely to have exercised. A strategy that survives a blackout, a dropped
    /// account update and a duplicate fill may still have no answer for the
    /// venue simply going away mid-run - which a real broker does, and which no
    /// in-process backtest can produce. It belongs here beside the others.
    ///
    /// Unlike every other arm it is terminal, so it consults no account scope
    /// and nothing clears it: there is no venue left to clear it on. Posting it
    /// is the last thing a scenario does.
    ///
    /// It also exists because the alternatives disappeared. A venue fault was
    /// previously reachable only by configuring an arrival family out of its
    /// usable range - `sigma_y` at 1e308 was the shipped fixture - and both
    /// knobs that allowed it are now bounded at admission. A fault path with no
    /// door is a fault path nothing can test.
    FaultTape,
}
